import { Router } from "../lib/http-kit";
import { selectAll, selectById, insert, update, del } from "@workspace/db";
import type { User } from "@workspace/db";
import { hashPassword, generateRandomPassword, SUPERADMIN, isSuperadmin } from "../lib/auth";
import { requireAuth } from "../middlewares/auth";

const router = Router();

const VALID_ROLES = ["admin", "supervisor", "agent"] as const;

router.get("/users", requireAuth, async (_req, res): Promise<void> => {
  const users = await selectAll<User>("users", { column: "created_at", dir: "ASC" });
  const merged = [
    { ...SUPERADMIN, createdAt: SUPERADMIN.createdAt.toISOString() },
    ...users.map((u) => ({ ...u, createdAt: u.createdAt.toISOString() })),
  ];
  res.json(merged);
});

router.post("/users", requireAuth, async (req, res): Promise<void> => {
  const body = (req.body as Record<string, unknown>) ?? {};

  const errors: string[] = [];
  const name = body.name;
  if (typeof name !== "string" || name.trim().length === 0) {
    errors.push("Name is required");
  }
  const email = body.email;
  if (typeof email !== "string" || email.trim().length === 0) {
    errors.push("Email is required");
  }
  const role = body.role;
  if (typeof role !== "string" || !VALID_ROLES.includes(role as any)) {
    errors.push("Role must be one of: admin, supervisor, agent");
  }
  let departmentId: number | null = null;
  if (body.departmentId !== null && body.departmentId !== undefined && body.departmentId !== "") {
    if (typeof body.departmentId === "number" && !isNaN(body.departmentId)) {
      departmentId = body.departmentId;
    } else if (typeof body.departmentId === "string") {
      const parsed = parseInt(body.departmentId, 10);
      if (!isNaN(parsed)) departmentId = parsed;
      else errors.push("Department ID must be a valid number");
    } else {
      errors.push("Department ID must be a valid number");
    }
  }
  const avatarUrl = typeof body.avatarUrl === "string" ? body.avatarUrl.trim() || null : null;
  const passwordRaw = body.password;
  const autoGenerated = typeof passwordRaw !== "string" || passwordRaw.length === 0;
  const plainPassword = autoGenerated ? generateRandomPassword() : passwordRaw;

  if (errors.length > 0) {
    res.status(400).json({ error: errors.join("; ") });
    return;
  }

  const passwordHash = await hashPassword(plainPassword);
  const user = await insert<User>("users", {
    name: (name as string).trim(),
    email: (email as string).toLowerCase().trim(),
    role,
    departmentId,
    avatarUrl,
    isActive: true,
    passwordHash,
  });

  const userJson = { ...user, createdAt: user.createdAt.toISOString() };

  if (autoGenerated) {
    res.status(201).json({ user: userJson, temporaryPassword: plainPassword });
  } else {
    res.status(201).json({ user: userJson });
  }
});

router.get("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid ID" });
    return;
  }
  const user = await selectById<User>("users", id);
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }
  res.json({ ...user, createdAt: user.createdAt.toISOString() });
});

router.patch("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid ID" });
    return;
  }
  const body = (req.body as Record<string, unknown>) ?? {};

  if (isSuperadmin(id)) {
    const allowedKeys = ["avatarUrl"];
    const updates: Record<string, unknown> = {};
    for (const key of allowedKeys) {
      if (key in body) {
        updates[key] = body[key] === null ? null : String(body[key]);
      }
    }
    if (Object.keys(updates).length === 0) {
      res.status(403).json({ error: "Superadmin can only update avatar" });
      return;
    }
    const updated = { ...SUPERADMIN, ...updates, createdAt: SUPERADMIN.createdAt.toISOString() };
    res.json(updated);
    return;
  }

  const updates: Record<string, unknown> = {};
  if ("name" in body) {
    if (typeof body.name !== "string" || (body.name as string).trim().length === 0) {
      res.status(400).json({ error: "Name must be a non-empty string" });
      return;
    }
    updates.name = (body.name as string).trim();
  }
  if ("email" in body) {
    if (typeof body.email !== "string" || (body.email as string).trim().length === 0) {
      res.status(400).json({ error: "Email must be a non-empty string" });
      return;
    }
    updates.email = (body.email as string).toLowerCase().trim();
  }
  if ("role" in body) {
    if (typeof body.role !== "string" || !VALID_ROLES.includes(body.role as any)) {
      res.status(400).json({ error: "Role must be one of: admin, supervisor, agent" });
      return;
    }
    updates.role = body.role;
  }
  if ("departmentId" in body) {
    if (body.departmentId === null || body.departmentId === undefined || body.departmentId === "") {
      updates.departmentId = null;
    } else {
      const parsed = typeof body.departmentId === "number" ? body.departmentId : parseInt(String(body.departmentId), 10);
      if (isNaN(parsed)) {
        res.status(400).json({ error: "Department ID must be a valid number" });
        return;
      }
      updates.departmentId = parsed;
    }
  }
  if ("avatarUrl" in body) {
    updates.avatarUrl = typeof body.avatarUrl === "string" ? (body.avatarUrl as string).trim() || null : null;
  }
  if ("isActive" in body) {
    if (typeof body.isActive !== "boolean") {
      res.status(400).json({ error: "isActive must be a boolean" });
      return;
    }
    updates.isActive = body.isActive;
  }

  if (Object.keys(updates).length === 0) {
    res.status(400).json({ error: "No valid fields to update" });
    return;
  }

  const user = await update<User>("users", id, updates);
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }
  res.json({ ...user, createdAt: user.createdAt.toISOString() });
});

router.post("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid ID" });
    return;
  }

  const user = await selectById<User>("users", id);
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }

  if (isSuperadmin(id)) {
    res.status(403).json({ error: "Superadmin password cannot be reset" });
    return;
  }

  const temporaryPassword = generateRandomPassword();
  const passwordHash = await hashPassword(temporaryPassword);
  await update("users", id, { passwordHash });

  res.json({ temporaryPassword });
});

router.delete("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid ID" });
    return;
  }

  if (isSuperadmin(id)) {
    res.status(403).json({ error: "Superadmin cannot be deleted" });
    return;
  }

  const user = await del<User>("users", id);
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }
  res.sendStatus(204);
});

export default router;
