import { Router, type IRouter } from "express";
import { eq } from "drizzle-orm";
import { db, usersTable } from "@workspace/db";
import {
  ListUsersResponse,
  CreateUserBody,
  GetUserParams,
  GetUserResponse,
  UpdateUserParams,
  UpdateUserBody,
  UpdateUserResponse,
  DeleteUserParams,
  ResetUserPasswordParams,
  ResetUserPasswordResponse,
} from "@workspace/api-zod";
import { hashPassword, generateRandomPassword, SUPERADMIN, isSuperadmin } from "../lib/auth";
import { requireAuth } from "../middlewares/auth";

const router: IRouter = Router();

router.get("/users", requireAuth, async (req, res): Promise<void> => {
  const users = await db.select().from(usersTable).orderBy(usersTable.createdAt);
  const merged = [
    { ...SUPERADMIN, createdAt: SUPERADMIN.createdAt.toISOString() },
    ...users.map(u => ({ ...u, createdAt: u.createdAt.toISOString() })),
  ];
  res.json(merged);
});

router.post("/users", requireAuth, async (req, res): Promise<void> => {
  const parsed = CreateUserBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  const { password, ...userData } = parsed.data;
  const autoGenerated = !password;
  const plainPassword = password ?? generateRandomPassword();
  const passwordHash = await hashPassword(plainPassword);

  const [user] = await db.insert(usersTable).values({ ...userData, passwordHash }).returning();

  const userJson = GetUserResponse.parse({ ...user, createdAt: user.createdAt.toISOString() });

  if (autoGenerated) {
    res.status(201).json({ user: userJson, temporaryPassword: plainPassword });
  } else {
    res.status(201).json({ user: userJson });
  }
});

router.get("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const params = GetUserParams.safeParse({ id: parseInt(raw, 10) });
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }
  const [user] = await db.select().from(usersTable).where(eq(usersTable.id, params.data.id));
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }
  res.json(GetUserResponse.parse({ ...user, createdAt: user.createdAt.toISOString() }));
});

router.patch("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const params = UpdateUserParams.safeParse({ id: parseInt(raw, 10) });
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }
  if (isSuperadmin(params.data.id)) {
    res.status(403).json({ error: "Superadmin cannot be modified" });
    return;
  }
  const parsed = UpdateUserBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  const [user] = await db.update(usersTable).set(parsed.data).where(eq(usersTable.id, params.data.id)).returning();
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }
  res.json(UpdateUserResponse.parse({ ...user, createdAt: user.createdAt.toISOString() }));
});

router.post("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const params = ResetUserPasswordParams.safeParse({ id: parseInt(raw, 10) });
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }
  const [user] = await db.select().from(usersTable).where(eq(usersTable.id, params.data.id));
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }

  if (isSuperadmin(params.data.id)) {
    res.status(403).json({ error: "Superadmin password cannot be reset" });
    return;
  }

  const temporaryPassword = generateRandomPassword();
  const passwordHash = await hashPassword(temporaryPassword);
  await db.update(usersTable).set({ passwordHash }).where(eq(usersTable.id, params.data.id));

  res.json(ResetUserPasswordResponse.parse({ temporaryPassword }));
});

router.delete("/users/:id", requireAuth, async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const params = DeleteUserParams.safeParse({ id: parseInt(raw, 10) });
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }
  if (isSuperadmin(params.data.id)) {
    res.status(403).json({ error: "Superadmin cannot be deleted" });
    return;
  }
  const [user] = await db.delete(usersTable).where(eq(usersTable.id, params.data.id)).returning();
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }
  res.sendStatus(204);
});

export default router;
